name: Release
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install
          pnpm run prepublish
          pnpm run release
