name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/checkout@v2
      - name: Install modules
        run: pnpm install
      - name: Run tests
        run: pnpm run test
